window.WORD_BANK = [
  "Innovation",
  "Integrity",
  "Customer delight",
  "Adaptability",
  "Empowerment",
  "Strategic partnerships",
  "Purpose-driven",
  "Forward thinking",
  "Data-guided",
  "Bold curiosity",
  "Outcome obsessed",
  "Sustainable growth",
  "Community impact",
  "Shared success",
  "Trusted advisors",
  "Global mindset",
  "Craftsmanship",
  "Inclusive culture",
  "Continuous learning",
  "Operational excellence",
  "Transparency",
  "Reliability",
  "Heart-led leadership",
  "Inventive spirit",
  "Challenge the norm",
  "Respect",
  "Accountability",
  "Passion",
  "Optimism",
  "Collaborative wins",
  "Trusted relationships",
  "Resilience",
  "People first",
  "Curate experiences",
  "Celebrate diversity",
  "Learning together",
  "Explore possibilities",
  "Shared purpose",
  "Lead with empathy",
  "Results with integrity",
  "Future ready",
  "Creative spark",
  "Digital craftsmanship",
  "Agility",
  "Courage",
  "Listening deeply",
  "Empathy",
  "Respectful candor",
  "Ambitious goals",
  "Exceed expectations",
  "Trailblazing",
  "Make it happen",
  "Better together",
  "Trusted stewards",
  "Strategic clarity",
  "Transformative ideas",
  "Customer-centric",
  "Vibrant culture",
  "Meaningful moments",
  "Purposeful design",
  "Crafted experiences",
  "We before me",
  "Inspire confidence",
  "Celebrate wins",
  "Steady hands",
  "Invent tomorrow",
  "Trusted execution",
  "Momentum",
  "Sincere partnerships",
  "Unified vision",
  "Delivering value",
  "Empowered voices",
  "Joy at work",
  "Quality without compromise",
  "Spark imagination",
  "Elevate each other",
  "Stewardship",
  "Operational rigor",
  "Human centered",
  "Ethical decisions",
  "Adaptive mindset",
  "Cultural guardians",
  "Make it memorable",
  "Iterate boldly",
  "Celebrate progress",
  "Global citizenship",
  "Uncover potential",
  "Nurture talent",
  "Curiosity",
  "Ingenuity",
  "Visionary thinking",
  "Inspire trust",
  "Lead with purpose",
  "Empowered by insight",
  "Dynamic energy",
  "Deliver the promise",
  "Craft the future",
  "Kindness",
  "Elevated standards",
  "Cohesive teams",
  "Playful experimentation",
  "Authenticity",
  "Spark possibilities",
  "Human connection",
  "Living our mission"
];
